[all]
ansible-01    ansible_host=192.168.1.10
k8s-master-01 ansible_host=192.168.1.11
k8s-worker-01 ansible_host=192.168.1.12
k8s-worker-02 ansible_host=192.168.1.13
k8s-worker-03 ansible_host=192.168.1.14

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_private_key_file=/home/ubuntu/.ssh/id_ansible
ansible_user=ubuntu